apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  version: 8.15.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
